# This is a basic workflow to help you get started with Actions

name: flugel.it

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
            
      - name: sdfsdf
        id: setting_output
        run: echo ::set-output name=ec2_uri::green
        
      - name: fssdf
        run: echo "The selected color is ${{ steps.setting_output.outputs.ec2_uri }}"         
        env:
          EC2_URI: "The selected color is ${{ steps.setting_output.outputs.ec2_uri }}"
        
      - name: afadf
        run:  echo $EC2_URI
        
        
      - name: curl
        uses: wei/curl@master
        with:
          args: $EC2_URI

      - name: checking py service
        run: curl $EC2_URI:8000/tags
        
